services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todoapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d todoapp" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # backend:
  #   build: ./backend
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - JWT_SECRET=${JWT_SECRET}      
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000/api/v1
  #   volumes:
  #     - node_modules:/app/node_modules
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

volumes:
  postgres_data:
  node_modules:
  


networks:
  app-network:
    driver: bridge
