"""fix_relationships_4

Revision ID: 13296bd3591c
Revises: 8597aa5e07b8
Create Date: 2024-10-28 13:05:26.813778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13296bd3591c'
down_revision = '8597aa5e07b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
