"""fix_relationships

Revision ID: 460b4db1450a
Revises: 13296bd3591c
Create Date: 2024-11-09 11:53:47.284213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460b4db1450a'
down_revision = '13296bd3591c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
