"""fix_relationships_3

Revision ID: 8597aa5e07b8
Revises: c31a465d865d
Create Date: 2024-10-27 20:42:44.661046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8597aa5e07b8'
down_revision = 'c31a465d865d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
