"""fix_relationships_2

Revision ID: c31a465d865d
Revises: 38e4bf0477a5
Create Date: 2024-10-26 13:22:20.679301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31a465d865d'
down_revision = '38e4bf0477a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
